"""
Pure delivery finalizer for already-governed orchestrator results.

This module turns an ``OrchestratorResult`` whose text was produced entirely
inside the MoralStack governed pipeline (validated speculative draft, compliance
regeneration, policy generate/rewrite, or a governed refusal) into a transport
neutral :class:`GovernedDelivery` value object.

Invariant (Plan 1 — governed delivery only):
    Delivered text = MoralStack governed result text.
    Delivered text != text generated by the wrapped/upstream client after
    governance has decided.

Purity rules (enforced by review, not by import side effects):
- pure function/dataclass module only;
- no wrapped/upstream client import;
- no policy model call;
- no DB/JSONL/event writes;
- no output-spec validation or rewrite.

It does not generate, rewrite, or revalidate any text. The only transformation
it performs is the fail-closed substitution of a deterministic safe refusal when
the governed content is blank — an empty answer must never be delivered.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from moralstack.orchestration.final_revalidation import DEFAULT_POST_REVALIDATION_REFUSAL

# New delivery sources introduced by Plan 1.
GOVERNED_TEXT_SOURCE = "governed"
GOVERNED_REFUSAL_SOURCE = "governed_refusal"
GOVERNED_PIPELINE_REFUSAL_SOURCE = "governed_pipeline_refusal"

# Historical ``final_text_source`` values that pre-date Plan 1. They are no
# longer produced by active delivery code, but historical UI rows, report
# loaders, and persisted JSONL/SQLite envelopes still carry them, so readers
# must keep tolerating these values.
HISTORICAL_FINAL_TEXT_SOURCES = frozenset(
    {
        "governed_draft",
        "upstream_regen",
        "safe_complete_upstream",
        "passthrough_on_error",
        "refusal_post_revalidation",
        "refusal_streaming_contract",
    }
)


@dataclass(frozen=True)
class GovernedDelivery:
    """Transport-neutral description of the text MoralStack will deliver.

    Attributes:
        text: the exact text to deliver to the caller.
        final_text_source: provenance marker (see ``GOVERNED_*`` constants).
        final_action: the action that governs delivery (may be downgraded to
            ``REFUSE`` when governed content was blank).
        finish_reason: OpenAI-compatible finish reason (``stop`` /
            ``content_filter``).
        original_final_action: the ``final_action`` recorded on the result
            metadata before any fail-closed downgrade, for audit.
        empty_governed_content: True when the governed content was
            blank/whitespace and the fail-closed refusal was substituted.
    """

    text: str
    final_text_source: str
    final_action: str
    finish_reason: str
    original_final_action: str
    empty_governed_content: bool = False


def finalize_delivery(result: Any, *, config: Any = None) -> GovernedDelivery:
    """Compute the governed delivery for an already-governed result.

    Args:
        result: an ``OrchestratorResult`` produced by the governed pipeline.
        config: reserved for forward-compatible delivery options (unused in
            Plan 1; Plan 2 may extend delivery metadata). Accepted so call
            sites do not need to change when options are introduced.

    Returns:
        A :class:`GovernedDelivery` describing exactly what to deliver. No
        upstream/wrapped client call is ever required to obtain this text.
    """
    del config  # Reserved for Plan 2; intentionally unused in Plan 1.

    response = getattr(result, "response", None)
    metadata = getattr(response, "metadata", None)
    original_final_action = str(getattr(metadata, "final_action", "") or "")
    content = getattr(response, "content", "") or ""

    if not content.strip():
        # Fail closed: governed pipeline produced no deliverable content.
        # Never deliver an empty answer; substitute a deterministic refusal.
        return GovernedDelivery(
            text=DEFAULT_POST_REVALIDATION_REFUSAL,
            final_text_source=GOVERNED_PIPELINE_REFUSAL_SOURCE,
            final_action="REFUSE",
            finish_reason="content_filter",
            original_final_action=original_final_action,
            empty_governed_content=True,
        )

    if original_final_action == "REFUSE":
        return GovernedDelivery(
            text=content,
            final_text_source=GOVERNED_REFUSAL_SOURCE,
            final_action="REFUSE",
            finish_reason="content_filter",
            original_final_action=original_final_action,
            empty_governed_content=False,
        )

    # NORMAL_COMPLETE / SAFE_COMPLETE: deliver the governed text verbatim.
    return GovernedDelivery(
        text=content,
        final_text_source=GOVERNED_TEXT_SOURCE,
        final_action=original_final_action or "NORMAL_COMPLETE",
        finish_reason="stop",
        original_final_action=original_final_action,
        empty_governed_content=False,
    )
