"""
Stable event_type identifiers for orchestration_events persistence.

Runtime code may emit subsets; the taxonomy is fixed so reports and UI can rely on names.
"""

from __future__ import annotations

# Speculative execution (future scheduler hooks)
SPECULATIVE_STARTED = "SPECULATIVE_STARTED"
SPECULATIVE_JOIN_REQUIRED = "SPECULATIVE_JOIN_REQUIRED"
SPECULATIVE_JOIN_SKIPPED = "SPECULATIVE_JOIN_SKIPPED"
SPECULATIVE_RESULT_USED = "SPECULATIVE_RESULT_USED"
SPECULATIVE_RESULT_DISCARDED = "SPECULATIVE_RESULT_DISCARDED"

# Parallel / short-circuit orchestration
PARALLEL_STRATEGY_SELECTED = "PARALLEL_STRATEGY_SELECTED"
CRITIC_SHORT_CIRCUIT_TRIGGERED = "CRITIC_SHORT_CIRCUIT_TRIGGERED"
PARALLEL_MODULE_CANCEL_ATTEMPTED = "PARALLEL_MODULE_CANCEL_ATTEMPTED"
PARALLEL_MODULE_CANCELLED = "PARALLEL_MODULE_CANCELLED"
PARALLEL_MODULE_COMPLETED_AFTER_SHORT_CIRCUIT = "PARALLEL_MODULE_COMPLETED_AFTER_SHORT_CIRCUIT"

# Principle retrieval / domain cache
RELEVANT_PRINCIPLES_RETRIEVED = "RELEVANT_PRINCIPLES_RETRIEVED"
RELEVANT_PRINCIPLES_REUSED = "RELEVANT_PRINCIPLES_REUSED"
DOMAIN_PREFILTER_CACHE_HIT = "DOMAIN_PREFILTER_CACHE_HIT"
DOMAIN_PREFILTER_CACHE_MISS = "DOMAIN_PREFILTER_CACHE_MISS"
DOMAIN_PREFILTER_CACHE_INVALIDATED = "DOMAIN_PREFILTER_CACHE_INVALIDATED"

# Simulator gating / execution
SIMULATOR_GATE_DECISION = "SIMULATOR_GATE_DECISION"
SIMULATOR_EXECUTED = "SIMULATOR_EXECUTED"
SIMULATOR_SKIPPED = "SIMULATOR_SKIPPED"

# Aggregated guidance (rewrite / soft revision)
AGGREGATED_GUIDANCE_EVALUATED = "AGGREGATED_GUIDANCE_EVALUATED"

# Convergence
CONVERGENCE_EVALUATED = "CONVERGENCE_EVALUATED"
EARLY_CONVERGENCE_ACCEPTED = "EARLY_CONVERGENCE_ACCEPTED"
EARLY_CONVERGENCE_REJECTED = "EARLY_CONVERGENCE_REJECTED"

# Conversation (multi-turn foundation; emit only when context is explicitly provided)
CONVERSATION_CONTEXT_ATTACHED = "CONVERSATION_CONTEXT_ATTACHED"
CONVERSATION_STATE_UPDATED = "CONVERSATION_STATE_UPDATED"

ALL_EVENT_TYPES: frozenset[str] = frozenset(
    {
        AGGREGATED_GUIDANCE_EVALUATED,
        SPECULATIVE_STARTED,
        SPECULATIVE_JOIN_REQUIRED,
        SPECULATIVE_JOIN_SKIPPED,
        SPECULATIVE_RESULT_USED,
        SPECULATIVE_RESULT_DISCARDED,
        PARALLEL_STRATEGY_SELECTED,
        CRITIC_SHORT_CIRCUIT_TRIGGERED,
        PARALLEL_MODULE_CANCEL_ATTEMPTED,
        PARALLEL_MODULE_CANCELLED,
        PARALLEL_MODULE_COMPLETED_AFTER_SHORT_CIRCUIT,
        RELEVANT_PRINCIPLES_RETRIEVED,
        RELEVANT_PRINCIPLES_REUSED,
        DOMAIN_PREFILTER_CACHE_HIT,
        DOMAIN_PREFILTER_CACHE_MISS,
        DOMAIN_PREFILTER_CACHE_INVALIDATED,
        SIMULATOR_GATE_DECISION,
        SIMULATOR_EXECUTED,
        SIMULATOR_SKIPPED,
        CONVERGENCE_EVALUATED,
        EARLY_CONVERGENCE_ACCEPTED,
        EARLY_CONVERGENCE_REJECTED,
        CONVERSATION_CONTEXT_ATTACHED,
        CONVERSATION_STATE_UPDATED,
    }
)
