"""
DeveloperContractComplianceLayer — main entry point.

Reference: dccl_specification_v0.3.md sections 6, 19.

Commit 1 (Foundation): scaffold only. The evaluate() method always returns
NO_CONTRACT. The structured path, LLM path, and safety override checks are
implemented in Commit 2.

The class is instantiable and integrable in the orchestrator, but is not yet
invoked by the controller (Commit 3 wires it in).
"""

from __future__ import annotations

import logging
from typing import Any

from moralstack.compliance.config import (
    EvaluationPathLiteral,
    get_dccl_confidence_threshold,
    get_dccl_enabled,
    get_dccl_evaluation_path,
    get_dccl_llm_max_tokens,
    get_dccl_llm_model,
    get_dccl_llm_timeout_ms,
    get_dccl_max_rules_per_contract,
    get_dccl_safety_override_strict,
)
from moralstack.compliance.types import (
    ComplianceDecision,
    ComplianceVerdict,
    EvaluationPath,
)

_LOG = logging.getLogger(__name__)


class DeveloperContractComplianceLayer:
    """
    Evaluates whether a user request invokes a behavior authorized by the
    developer's contract, and coordinates the pipeline accordingly.

    Lifecycle:
        layer = DeveloperContractComplianceLayer(policy=...)  # injection of LLM policy for Commit 2
        verdict = layer.evaluate(request, speculative_draft, risk_estimation)

    Configuration is read from MORALSTACK_DCCL_* env vars at construction time.
    Per-request overrides are not supported in Commit 1.
    """

    def __init__(
        self,
        policy: Any | None = None,
    ) -> None:
        """
        Args:
            policy: LLM policy used by the LLM path (Commit 2). Optional in Commit 1
                because evaluate() does not yet call the LLM.
        """
        self._policy = policy
        self._enabled = get_dccl_enabled()
        self._evaluation_path: EvaluationPathLiteral = get_dccl_evaluation_path()
        self._llm_model = get_dccl_llm_model()
        self._llm_timeout_ms = get_dccl_llm_timeout_ms()
        self._llm_max_tokens = get_dccl_llm_max_tokens()
        self._confidence_threshold = get_dccl_confidence_threshold()
        self._max_rules_per_contract = get_dccl_max_rules_per_contract()
        self._safety_override_strict = get_dccl_safety_override_strict()

        if self._enabled:
            _LOG.debug(
                "DCCL initialized: path=%s, model=%s, threshold=%.2f, strict_safety=%s",
                self._evaluation_path, self._llm_model, self._confidence_threshold,
                self._safety_override_strict,
            )

    @property
    def enabled(self) -> bool:
        return self._enabled

    @property
    def confidence_threshold(self) -> float:
        return self._confidence_threshold

    def evaluate(
        self,
        request: Any,
        speculative_draft: str = "",
        risk_estimation: Any | None = None,
    ) -> ComplianceVerdict:
        """
        Evaluate the request against the developer contract.

        Commit 1 (Foundation): always returns NO_CONTRACT. The actual evaluation
        logic (structured path, LLM path, safety override) is implemented in Commit 2.

        Args:
            request: ProcessedRequest with attached developer_contract (or None).
            speculative_draft: the response generated by the policy speculative,
                used to validate that the draft executes the matched rule.
            risk_estimation: optional output of risk_estimator, used as sanity check.

        Returns:
            ComplianceVerdict. In Commit 1, always NO_CONTRACT.
        """
        # Commit 1 stub: DCCL exists but is functionally inert.
        return ComplianceVerdict(
            decision=ComplianceDecision.NO_CONTRACT,
            evaluation_path=EvaluationPath.SKIPPED,
            rationale="DCCL Foundation commit; evaluation logic ships in Commit 2.",
            duration_ms=0.0,
        )
